### PR TITLE
Add script links to Info tab

### PR DESCRIPTION
**Pull request by ronso0**
image

### CODE REVIEW

**Comment by ronso0** [comment]
I'll check the focus behaviour of all elements again.. seems some labels can be focused with Tab

**Comment by ronso0** [comment]
> I'll check the focus behaviour of all elements again.. seems some labels can be focused with Tab

forget about it: focus was on Cancel, etc... (my theme has a poor focus indicator), but yet when I Tab through the Info tab there's an invisble item between the combobox and the mapping links. won't fix

**Comment by ronso0** [comment]
ready for merge.

**Comment by Be-ing** [comment]
thanks

**Comment by Be-ing** [comment]
Your C++ is getting better :)

**Comment by ronso0** [comment]
my trial-n-error is gettin more effective -_o

**Pull request merged**
