### PR TITLE
ChannelMixer: Use range-based for loops

### PR DESCRIPTION
**Pull request by uklotzde**
...and the argument should passed as a const-ref instead of a pointer.

Still many opportunities for getting the code into a readable and maintainable state. I don't have the intention to do this ;)

### CODE REVIEW

**Comment by Be-ing** [comment]
Build is broken

**Comment by Be-ing** [comment]
I don't know why CI keeps failing with network errors...

**Comment by uklotzde** [comment]
Merging main into the PR branch could have prevented this. If it doesn't work now I will close the PR.

**Comment by Be-ing** [comment]
Let's just redo this as a PR for main after merging https://github.com/mixxxdj/mixxx/pull/1966

**Pull request closed without merging**
