### PR TITLE
fresh view

### PR DESCRIPTION
**Pull request by ronso0**

### CODE REVIEW

**Comment by Be-ing** [comment]
Looks like the aspect ratio of the knobs got skewed. They look stretched vertically. Also, the outer rings around the knobs are not showing.

**Comment by ronso0** [comment]
Yes, I removed the rings, this could save 20px of vertical space while
they are still useful.
What are the rings good for anyway? The small knobs

I can fix the knobs' appearance, but the question is: doy you like the
general idea?

Do you like how BPM controls are arranged in normal deck mode?

**Comment by Be-ing** [comment]
I like the idea of shrinking the knobs. They are the limiting factor for the vertical height of the decks + mixer. I do not know if I like removing the outer rings. Shrinking the knobs without the outer rings might look better if the knobs are made circular again.

> Do you like how BPM controls are arranged in normal deck mode?

Not really. I don't like how controls for BPM, key, and beatgrid are hidden behind clicks. That is a big discoverability issue. I didn't know those existed for a long time. However, I don't really want to put in the work to design a better way for Deere right now. If you'd like to try that, awesome. Please open a different PR for that though. I'd like to keep each PR small and focused.

**Comment by ronso0** [comment]
> Not really. I don't like how controls for BPM, key, and beatgrid are
hidden behind clicks.

I only refered to Sync, *+*, *-* and Rate display (my 2nd commit in the PR)
There, I didn't change the functionality at all, just the arrangement.

Beatgrid and Key buttons is another issue...

**Comment by Be-ing** [comment]
> I only refered to Sync, *+*, *-* and Rate display (my 2nd commit in the PR) There, I didn't change the functionality at all, just the arrangement.

Oh, yes, I do like that.

**Comment by ronso0** [comment]
Can you reject the 1st commit about EQ knobs or should I a start a new for Sync stuff only?

**Comment by ronso0** [comment]
I'll just close this PR and start a new one for Sync button etc.
Need to learn about cherry-pick and stuff..

**Pull request closed without merging**
